# Generated by Django 4.2.13 on 2024-07-26 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
